name: debug ssh

on:
  push:

jobs:
  test:
    runs-on: [self-hosted]
    steps:
    - run: env
    - run: echo $$
    - run: ls -l /proc/$$/fd
    - run: if [ -t 1 ] ; then echo terminal; else echo "not a terminal"; fi
    - run: cat /etc/ssh/ssh_config
    - run: cat ~/.ssh/known_hosts || true
    - run: ls -l /dev/tty /dev/console /dev/null
    - run: ssh -vvv gitlab.com || true
    - run: cat ~/.ssh/known_hosts || true
