name: debug ssh

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: cat /etc/ssh/ssh_config
    - run: cat ~/.ssh/known_hosts || true
    - run: ssh -vvv gitlab.com || true
    - run: cat ~/.ssh/known_hosts || true
